### ISSUE TITLE
Revisions 

### ISSUE THREAD

**Issue by grubalubadubdub** [pedrohrfranca/pedros_ToDoIst#1]
Hi Pedro, here are some high-level observations that I've observed.

For each of these, create a separate branch and add me as a reviewer before merging.
- Move the add task button to the main dropdown instead of the nav bar
- Get rid of the placeholder text (Lorem Ipsum)
- Sorted by priority (see if you can implement global sorting)
- Let's use async/await methods and not get stuck in .then.catch changing

**Comment by pedrohrfranca** [comment]
Ok, I'll always create a separate branch first, and send you before doing the merge.

- Move the add task button to the main dropdown instead of the nav bar ✅

- Get rid of the placeholder text (Lorem Ipsum) ✅

- Sorted by priority (see if you can implement global sorting)✅

- Let's use async/await methods and not get stuck in .then.catch changing ✅

**Comment by pedrohrfranca** [comment]
Just did the push on PEDROS-BRANCH of changes made from the last comments.

**Comment by grubalubadubdub** [comment]
Hi Pedro, thanks for letting me know. I'll take a look; could you next time make a branch for each change so I can review small  PRs and give you better feedback

**Comment by pedrohrfranca** [comment]
Yeah, Sure. I'll do that.

**Comment by pedrohrfranca** [comment]
Hi Eduard, Did some changes and created a new Branch. Take a look later 👊🏻

**Comment by grubalubadubdub** [comment]
Thanks for creating a new branch, only comment about that is going forward please create a new branch per feature. That way the changes are isolated and we can focus on a single feature at a time.

Could you create a pull request for the most recent branch? I'll put my review in there as well

**Comment by grubalubadubdub** [comment]
![Screenshot 2023-11-12 at 5 25 38 PM](https://github.com/pedrohrfranca/pedros_ToDoIst/assets/6559706/460bc169-4e8b-4928-a958-618146d0639f)
I see that if I don't add a due date it's null

**Comment by grubalubadubdub** [comment]
![Screenshot 2023-11-12 at 5 26 01 PM](https://github.com/pedrohrfranca/pedros_ToDoIst/assets/6559706/b8c130ab-f7ed-42bd-9381-9850042956b9)
For these 2, I would add some labels so people know what to select :)

**Comment by grubalubadubdub** [comment]
Pretty good otherwise, and we'll rebuild this using React after these minor cosmetic changes :)

**Comment by pedrohrfranca** [comment]
That's great Eduard, thanks. I just did the PR, if something get wrong let me know.

**Comment by pedrohrfranca** [comment]
About the date/null, I'll fix it.

**Comment by grubalubadubdub** [comment]
Thanks Pedro! 

Only notes are that each feature or change should get a PR, small PRs move faster when you're working in a team and a good habit to follow.
