### ISSUE TITLE
Split up Javascript File by functionality

### ISSUE THREAD

**Issue by grubalubadubdub** [pedrohrfranca/pedros_ToDoIst#3]
Hi Pedro, 

Goodjob on updating the Javascript, happy to see you're implementing these changes rather quickly. 🎉 

Let's do another change that will make this more readable and a step in the refactoring process
- Split the functionality into each file (add/remove/complete) etc.
- Follow the single responsibility principle to allow a single change to occur rather than having multiple changes in a given function.
- What happens if an addEventHandler already exists for a given element? Do you add another event handler to the HTML element?

**Comment by pedrohrfranca** [comment]
I just create a new BRANCH and Splited the functionality, and did some changes to be a better code principles especially at addAtividades.js who was so big and confused.

**Comment by pedrohrfranca** [comment]
Didn't get what you mean with this comment : What happens if an addEventHandler already exists for a given element? Do you add another event handler to the HTML element?

**Comment by grubalubadubdub** [comment]
@pedrohrfranca Sounds good, let's talk through some of it today :)
